import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import { container } from "../../../app/di/container";
import { routes } from "../../../app/navigation/routes";
import type { ApiExportFile } from "../../../infra/api/MocapApiClient";
import { Button } from "../../../ui/components/Button";
import { Card } from "../../../ui/components/Card";
import { Screen, ScreenHeader } from "../../../ui/components/Screen";
import { colors, radii, spacing, typography } from "../../../ui/theme";

type RouteParams = {
  localTakeId?: string;
  remoteTakeId?: string;
  jobId?: string;
};

type Nav = any;

function formatBytes(bytes: number | null) {
  if (!bytes || bytes <= 0) return "size pending";
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function formatLabel(format: string) {
  return format.replace(/_/g, " ").toUpperCase();
}

export default function ExportResultScreen() {
  const navigation = useNavigation<Nav>();
  const route = useRoute<any>();
  const params = route?.params as RouteParams | undefined;
  const remoteTakeId = params?.remoteTakeId;

  const [exports, setExports] = useState<readonly ApiExportFile[]>([]);
  const [busyExportId, setBusyExportId] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const primary = useMemo(
    () =>
      exports.find((file) => file.format === "bvh") ??
      exports.find((file) => file.format === "solved_motion_json") ??
      exports[0],
    [exports],
  );

  const refresh = useCallback(async () => {
    if (!remoteTakeId) {
      setErrorMessage("Missing remote take id.");
      return;
    }
    try {
      const list = await container.exportService.listExports(remoteTakeId);
      setExports(list);
      setErrorMessage(null);
    } catch (error: any) {
      setErrorMessage(error?.message ?? "Could not load backend exports.");
    }
  }, [remoteTakeId]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  const openExport = useCallback(async (file: ApiExportFile) => {
    setBusyExportId(file.id);
    try {
      const signed = await container.exportService.getDownloadUrl(file.id);
      const supported = await Linking.canOpenURL(signed.downloadUrl);
      if (!supported) {
        Alert.alert("Download URL", signed.downloadUrl);
        return;
      }
      await Linking.openURL(signed.downloadUrl);
    } catch (error: any) {
      Alert.alert("Download failed", error?.message ?? "Could not open export URL.");
    } finally {
      setBusyExportId(null);
    }
  }, []);

  return (
    <Screen scroll background={errorMessage ? "danger" : "accent"} contentContainerStyle={styles.container}>
      <ScreenHeader
        eyebrow="Result"
        title="Backend exports are ready"
        subtitle="Files below are generated by the backend worker from the uploaded source video, not by the mobile debug exporter."
        right={<Button label="Refresh" variant="ghost" size="sm" onPress={refresh} />}
      />

      <Card tone="accent" style={styles.card}>
        <Text style={styles.label}>Primary handoff</Text>
        <Text style={styles.title}>{primary ? formatLabel(primary.format) : "Waiting"}</Text>
        <Text style={styles.message}>
          {primary
            ? `${formatBytes(primary.fileSizeBytes)} · ${new Date(primary.createdAt).toLocaleString()}`
            : "Export indexing has not completed yet."}
        </Text>
        {primary ? (
          <Button
            label="Download primary"
            loading={busyExportId === primary.id}
            onPress={() => openExport(primary)}
          />
        ) : null}
      </Card>

      {errorMessage ? (
        <Card tone="danger" style={styles.card}>
          <Text style={styles.label}>Issue</Text>
          <Text style={styles.message}>{errorMessage}</Text>
        </Card>
      ) : null}

      <Card tone="muted" style={styles.card}>
        <View style={styles.listHeader}>
          <Text style={styles.label}>Artifacts</Text>
          <Text style={styles.meta}>{exports.length} files</Text>
        </View>
        {exports.map((file) => (
          <Pressable
            key={file.id}
            onPress={() => openExport(file)}
            style={({ pressed }) => [
              styles.exportRow,
              pressed ? styles.exportRowPressed : null,
            ]}
          >
            <View style={styles.exportCopy}>
              <Text style={styles.exportTitle}>{formatLabel(file.format)}</Text>
              <Text style={styles.meta}>
                {file.preset} · {formatBytes(file.fileSizeBytes)}
              </Text>
            </View>
            <Text style={styles.download}>
              {busyExportId === file.id ? "..." : "OPEN"}
            </Text>
          </Pressable>
        ))}
        {exports.length === 0 ? (
          <Text style={styles.message}>No export files returned yet.</Text>
        ) : null}
      </Card>

      <View style={styles.actions}>
        {params?.localTakeId ? (
          <Button
            label="Review local"
            variant="secondary"
            onPress={() =>
              navigation.navigate(routes.Review, { takeId: params.localTakeId })
            }
          />
        ) : null}
        <Button
          label="Back to capture"
          variant="ghost"
          onPress={() => navigation.navigate("Tabs", { screen: routes.Capture })}
        />
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  container: {
    gap: spacing.md,
    paddingBottom: spacing["3xl"],
  },
  card: {
    gap: spacing.sm,
  },
  label: {
    ...typography.label.md,
    color: colors.textMuted,
  },
  title: {
    ...typography.title.card,
    color: colors.textPrimary,
  },
  message: {
    ...typography.body.md,
    color: colors.textSecondary,
  },
  meta: {
    ...typography.mono.sm,
    color: colors.textMuted,
  },
  listHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  exportRow: {
    minHeight: 66,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    padding: spacing.md,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  exportRowPressed: {
    transform: [{ scale: 0.99 }],
  },
  exportCopy: {
    flex: 1,
    gap: spacing.xxs,
  },
  exportTitle: {
    ...typography.label.md,
    color: colors.textPrimary,
  },
  download: {
    ...typography.label.sm,
    color: colors.accent,
  },
  actions: {
    gap: spacing.sm,
  },
});
